[project]
name = "genai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "dotenv>=0.9.9",
    "gradio>=5.34.0",
    "langchain>=0.3.25",
    "openai>=1.87.0",
]
